apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-standard-replacement
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - ""
volumeBindingMode: WaitForFirstConsumer
